// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbnj0DcGNFZn2DdZooBbKDnR__p9VHrk',
    appId: '1:173433181560:android:ea464c752cb526b8f1a48d',
    messagingSenderId: '173433181560',
    projectId: 'biometric-7b07e',
    databaseURL: 'https://biometric-7b07e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biometric-7b07e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaWK9whkz10i7pDVmZ__st5NlPhfbbVg',
    appId: '1:173433181560:ios:010efaaa66f1bf08f1a48d',
    messagingSenderId: '173433181560',
    projectId: 'biometric-7b07e',
    databaseURL: 'https://biometric-7b07e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biometric-7b07e.firebasestorage.app',
    iosBundleId: 'com.example.h8FliBiometricStarter',
  );

}